### ISSUE TITLE
Setup Pypi publish workflow

### ISSUE THREAD

**Issue by bushshrub** [approx-ml/approx#14]
Currently, our CI has no workflow to publish to PyPi. This would be useful for the v0.1 release.

**Comment by ma7dev** [comment]
Example of how to setup one:

```yaml
name: publish_package_to_pypi

on:
  push:
    branches: ['main']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      ...
      - name: Publish Package
        run: |
          echo "Building package..."
          python -m poetry build
          echo "Publish package..."
          python -m poetry publish --username=${{ secrets.PYPIUSERNAME }} --password=${{ secrets.PYPIPASSWORD }}
```
