### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by ma7dev** [approx-ml/approx#8]
- [x] ci.yml
- [ ] publish.yml
- [x] docs.yml
- [x] lint.yml

### ci.yml

```yaml
name: Run tests

on:
  push:
    branches:
      - main
      - develop
      - dev/*
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - README.md
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
      - develop
      - dev/*
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - README.md

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      ...
      - name: Checkout repository
        uses: https://github.com/actions/checkout/tree/v2v2
      - name: Run tests
        run: |
          echo "Running tests..."
          python -m pytest tests
```

### publish.yml
```yaml
name: publish_package_to_pypi

on:
  push:
    branches: ['main']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      ...
      - name: Publish Package
        run: |
          echo "Building package..."
          python -m poetry build
          echo "Publish package..."
          python -m poetry publish --username=${{ secrets.PYPIUSERNAME }} --password=${{ secrets.PYPIPASSWORD }}
```
